env_str: rooms_env:RoomsEnv
num_iterations: 20000
replay_buffer_size: 20000
warm_start: 2000
batch_size: 32
target_update_interval: 10
epsilon_decay_until: 20000
max_epsilon: 1.0
min_epsilon: 0.1
gamma: 0.9
history_block_size: 8
lstm_params:
  hidden_size: 96
  num_layers: 2
  embedding_dim: 96
  bidirectional: false
mlp_params:
  hidden_size: 96
  num_hidden_layers: 1
  dueling_dqn: true
num_samples_for_results:
  val: 5
  test: 10
validation_interval: 5
plotting_interval: 20
train_seed: 9
test_seed: 4
device: cpu
env_config:
  question_prob: 1.0
  terminates_at: 99
  randomize_observations: objects
  room_size: xl-different-prob
  rewards:
    correct: 1
    wrong: 0
    partial: 0
  make_everything_static: false
  num_total_questions: 1000
  question_interval: 1
  include_walls_in_observations: true
  deterministic_objects: false
default_root_dir: ./training-results/baselines/room_size=xl/history_block_size=8/
run_handcrafted_baselines: true
