env_str: rooms_env:RoomsEnv
num_iterations: 10000
replay_buffer_size: 10000
warm_start: 1000
batch_size: 32
target_update_interval: 10
epsilon_decay_until: 10000
max_epsilon: 1.0
min_epsilon: 0.1
gamma:
  mm: 0.99
  explore: 0.9
capacity:
  episodic: 12
  semantic: 12
  short: 1
pretrain_semantic: false
lstm_params:
  num_layers: 2
  embedding_dim: 64
  hidden_size: 64
  bidirectional: false
  max_timesteps: 100
  max_strength: 100
  relu_for_attention: true
mlp_params:
  hidden_size: 64
  num_hidden_layers: 1
  dueling_dqn: true
num_samples_for_results:
  val: 5
  test: 10
validation_interval: 5
plotting_interval: 50
train_seed: 9
test_seed: 4
device: cpu
qa_function: episodic_semantic
explore_policy_heuristic: avoid_walls
env_config:
  question_prob: 1.0
  terminates_at: 99
  randomize_observations: objects
  room_size: xl-different-prob
  rewards:
    correct: 1
    wrong: 0
    partial: 0
  make_everything_static: false
  num_total_questions: 1000
  question_interval: 1
  include_walls_in_observations: true
ddqn: true
default_root_dir: ./training-results/dqn/room_size=xl/capacity=24/episodic=12_semantic=12/pretrain_semantic=False
